CREATE DATABASE order_service_db;
USE order_service_db;

CREATE TABLE orders (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    user_id BINARY(16) NOT NULL,
    ticker VARCHAR(10) NOT NULL,
    quantity DECIMAL(65, 30) NOT NULL,
    ticker_price DECIMAL(65, 30) NOT NULL,
    total DECIMAL(65, 30) NOT NULL,
    type ENUM('BUY', 'SELL') NOT NULL,
    min_price DECIMAL(65, 30) NULL,
    max_price DECIMAL(65, 30) NULL,
    status ENUM('PENDING', 'FILLED', 'CANCELED') NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);